import pygame
import time
pygame.init()
dolphin_1 = pygame.mixer.Sound("/Users/eclancy/Downloads/dolphin.wav")
owl_2 = pygame.mixer.Sound("/Users/eclancy/Downloads/owl.wav")
cow_3 = pygame.mixer.Sound("/Users/eclancy/Downloads/cow.wav")
bird_4 = pygame.mixer.Sound("/Users/eclancy/Downloads/bird.wav")
donkey_5 = pygame.mixer.Sound("/Users/eclancy/Downloads/donkey.wav")
duck_6 = pygame.mixer.Sound("/Users/eclancy/Downloads/duck.wav")
monkey_7 = pygame.mixer.Sound("/Users/eclancy/Downloads/monkey.wav")
horse_8 = pygame.mixer.Sound("/Users/eclancy/Downloads/horse.wav")
lion_9 = pygame.mixer.Sound("/Users/eclancy/Downloads/lion.wav")
pig_0 = pygame.mixer.Sound("/Users/eclancy/Downloads/pig.wav")


cow_3.play()
time.sleep(1.3)
dolphin_1.play()
time.sleep(1.3)
bird_4.play()
time.sleep(1.3)
dolphin_1.play()
time.sleep(1.3)
donkey_5.play()
time.sleep(1.3)
lion_9.play()
time.sleep(1.3)
owl_2.play()
time.sleep(1.3)
duck_6.play()
time.sleep(1.3)
donkey_5.play()
time.sleep(1.3)
cow_3.play()
time.sleep(1.3)
donkey_5.play()
time.sleep(1.3)
horse_8.play()
time.sleep(1.3)
lion_9.play()
time.sleep(1.3)
monkey_7.play()
time.sleep(1.3)
lion_9.play()
time.sleep(1.3)
cow_3.play()
time.sleep(1.3)
owl_2.play()
time.sleep(1.3)
cow_3.play()
time.sleep(1.3)
horse_8.play()
time.sleep(1.3)
bird_4.play()
time.sleep(1.3)
duck_6.play()
time.sleep(1.3)
owl_2.play()
time.sleep(1.3)
duck_6.play()
time.sleep(1.3)
bird_4.play()
time.sleep(1.3)
cow_3.play()
time.sleep(1.3)
cow_3.play()
time.sleep(1.3)
horse_8.play()
time.sleep(1.3)
cow_3.play()
time.sleep(1.3)
owl_2.play()
time.sleep(1.3)
monkey_7.play()
time.sleep(1.3)
lion_9.play()
time.sleep(1.3)
donkey_5.play()
time.sleep(1.3)
