#this one plays music from the wav files it is assigned too
#the variables are incorrect (copied and pasted from past py)

import pygame
import time
pygame.init()
dolphin_1 = pygame.mixer.Sound("/Users/eclancy/Downloads/589_kb_070_mega_wave_drum.aif.wav")
owl_2 = pygame.mixer.Sound("/Users/eclancy/Downloads/1658_kb_050_glitch-hop-serenade.aif.wav")
cow_3 = pygame.mixer.Sound("/Users/eclancy/Downloads/1071_kb_077_hip-hat-trap-hh.wav.wav")
bird_4 = pygame.mixer.Sound("/Users/eclancy/Downloads/1181_kb_070_rim-and-giant-drums.aif.wav")
donkey_5 = pygame.mixer.Sound("/Users/eclancy/Downloads/350_kb_059_808-hiphop.aif.wav")
duck_6 = pygame.mixer.Sound("/Users/eclancy/Downloads/295_kb_070_bongo-lo-hi.aif.wav")
monkey_7 = pygame.mixer.Sound("/Users/eclancy/Downloads/295_kb_070_bongo-hi-lo.aif.wav")
horse_8 = pygame.mixer.Sound("/Users/eclancy/Downloads/173_kb_121_hard-latin-bell.wav.wav")
lion_9 = pygame.mixer.Sound("/Users/eclancy/Downloads/681_kb_122_ron-wagner-tabla.aif.wav")
pig_0 = pygame.mixer.Sound("/Users/eclancy/Downloads/1896kb131-offsnare-ekoerswav.wav")


cow_3.play()
time.sleep(1.3)
dolphin_1.play()
time.sleep(1.3)
bird_4.play()
time.sleep(1.3)
dolphin_1.play()
time.sleep(1.3)
donkey_5.play()
time.sleep(1.3)
lion_9.play()
time.sleep(1.3)
owl_2.play()
time.sleep(1.3)
duck_6.play()
time.sleep(1.3)
donkey_5.play()
time.sleep(1.3)
cow_3.play()
time.sleep(1.3)
donkey_5.play()
time.sleep(1.3)
horse_8.play()
time.sleep(1.3)
lion_9.play()
time.sleep(1.3)
monkey_7.play()
time.sleep(1.3)
lion_9.play()
time.sleep(1.3)
cow_3.play()
time.sleep(1.3)
owl_2.play()
time.sleep(1.3)
cow_3.play()
time.sleep(1.3)
horse_8.play()
time.sleep(1.3)
bird_4.play()
time.sleep(1.3)
duck_6.play()
time.sleep(1.3)
owl_2.play()
time.sleep(1.3)
duck_6.play()
time.sleep(1.3)
bird_4.play()
time.sleep(1.3)
cow_3.play()
time.sleep(1.3)
cow_3.play()
time.sleep(1.3)
horse_8.play()
time.sleep(1.3)
cow_3.play()
time.sleep(1.3)
owl_2.play()
time.sleep(1.3)
monkey_7.play()
time.sleep(1.3)
lion_9.play()
time.sleep(1.3)
donkey_5.play()
time.sleep(1.3)
